name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    env:
      #se for usar algum valor gerado por usuario ou github, sempre use variaveis
      TITLE: ${{ github.event.issue.title }}
    steps:
      - name: Assign label
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$TITLE" == *"bug"* ]]; then 
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi